before_script:
  - bundle install
  - echo $MASTER_KEY > config/master.key

cache:
  paths:
    - tmp/cache/

database:
  stage: build
  script: RAILS_ENV=test bundle exec rails db:reset

rubocop:
  script: bundle exec rubocop -R

reek:
  script: bundle exec reek

haml-lint:
  script: bundle exec haml-lint

factory-lint:
  script: bundle exec rails factory_bot:lint

brakeman:
  script: bundle exec brakeman -q --no-pager

test:
  script:
    - bundle exec rails test

staging:
  stage: deploy
  script: bundle exec cap staging deploy
  environment:
    name: staging
  only:
    - master
