before_script:
  - bundle install
  - echo $MASTER_KEY > config/master.key

database:
  stage: build
  script: RAILS_ENV=test bundle exec rails db:reset

rubocop:
  script: bundle exec rubocop -R --color

reek:
  script: bundle exec reek --color

haml-lint:
  script: bundle exec haml-lint --color

factory-lint:
  script: bundle exec rails factory_bot:lint

test:
  script:
    - bundle exec rails test --color

staging:
  stage: deploy
  script: bundle exec cap staging deploy
  environment:
    name: staging
  only:
    - master
