linters:
  LineLength:
    enabled: false

RuboCop:
  enabled: true
  # These cops are incredibly noisy when it comes to HAML templates, so we
  # ignore them.
  ignored_cops:
    - Lint/BlockAlignment
    - Lint/EndAlignment
    - Lint/Void
    - Metrics/BlockLength
    - Metrics/LineLength
    - Style/AlignParameters
    - Style/BlockNesting
    - Style/ElseAlignment
    - Style/EndOfLine
    - Style/FileName
    - Style/FinalNewline
    - Style/FrozenStringLiteralComment
    - Style/IfUnlessModifier
    - Style/IndentationWidth
    - Style/Next
    - Style/TrailingBlankLines
    - Style/TrailingWhitespace
    - Style/WhileUntilModifier
