AllCops:
  TargetRubyVersion:
    2.5.1
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/*
    - db/default/*
    - config/initializers/*
    - config/environments/*
    - bin/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Rakefile

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - db/seeds.rb
    - test/controllers/*

Metrics/ClassLength:
  Exclude:
    - test/controllers/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
